#!/bin/bash
# root.exe -b -q 'run.C(0,0,0,"AnalysisResults.root",".","")'
# root.exe -b -q 'run.C(0,0,1,"AnalysisResults.root",".","")'
# root.exe -b -q 'run.C(0,0,2,"AnalysisResults.root",".","")'
# root.exe -b -q 'run.C(0,0,3,"AnalysisResults.root",".","")'
# root.exe -b -q 'run.C(0,0,4,"AnalysisResults.root",".","")'
# root.exe -b -q 'run.C(0,0,5,"AnalysisResults.root",".","")'
# root.exe -b -q 'run.C(0,0,6,"AnalysisResults.root",".","")'
# root.exe -b -q 'run.C(0,0,7,"AnalysisResults.root",".","")'
# root.exe -b -q 'run.C(0,0,8,"AnalysisResults.root",".","")'
# root.exe -b -q 'run.C(0,0,9,"AnalysisResults.root",".","")'
# root.exe -b -q 'run.C(0,0,10,"AnalysisResults.root",".","")'
# root.exe -b -q 'run.C(0,0,11,"AnalysisResults.root",".","")'
root.exe -b -q 'run.C(0,0,12,"AnalysisResults.root",".","")'

